"""removing team fg attempts

Revision ID: 08ad56e0dc1f
Revises: 97347d6b6812
Create Date: 2025-11-02 15:49:53.710420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08ad56e0dc1f'
down_revision: Union[str, None] = '97347d6b6812'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kicks',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('opp_id', sa.Integer(), nullable=False),
    sa.Column('fga', sa.Integer(), nullable=False),
    sa.Column('fgm', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opp_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id', 'game_id')
    )
    op.drop_column('football_team_stats', 'fg_conv')
    op.drop_column('football_team_stats', 'fg_att')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('football_team_stats', sa.Column('fg_att', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('football_team_stats', sa.Column('fg_conv', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_table('kicks')
    # ### end Alembic commands ###
