"""adds player stats

Revision ID: 23673d16539b
Revises: 7a00ca15f365
Create Date: 2025-08-24 09:52:35.865094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23673d16539b'
down_revision: Union[str, None] = '7a00ca15f365'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('at_bat_types',
    sa.Column('at_bat_type_id', sa.Integer(), nullable=False),
    sa.Column('at_bat_type_name', sa.String(), nullable=False),
    sa.Column('is_pa', sa.Boolean(), nullable=False),
    sa.Column('is_ab', sa.Boolean(), nullable=False),
    sa.Column('is_ob', sa.Boolean(), nullable=False),
    sa.Column('is_hit', sa.Boolean(), nullable=False),
    sa.Column('num_bases', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('at_bat_type_id')
    )
    op.create_table('basketball_shot_types',
    sa.Column('shot_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('shot_type_id')
    )
    op.create_table('pitch_result_types',
    sa.Column('pitch_result_name', sa.String(), nullable=False),
    sa.Column('pitch_result_id', sa.Integer(), nullable=False),
    sa.Column('is_strike', sa.Boolean(), nullable=False),
    sa.Column('is_swing', sa.Boolean(), nullable=False),
    sa.Column('is_contact', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('pitch_result_name'),
    sa.UniqueConstraint('pitch_result_id')
    )
    op.create_table('at_bats',
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('play_num', sa.String(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('opp_id', sa.Integer(), nullable=False),
    sa.Column('pitcher_id', sa.Integer(), nullable=False),
    sa.Column('batter_id', sa.Integer(), nullable=False),
    sa.Column('at_bat_type_id', sa.Integer(), nullable=False),
    sa.Column('hit_hardness', sa.Integer(), nullable=True),
    sa.Column('hit_style', sa.Integer(), nullable=True),
    sa.Column('hit_distance', sa.Integer(), nullable=True),
    sa.Column('hit_angle', sa.Integer(), nullable=True),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['at_bat_type_id'], ['at_bat_types.at_bat_type_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['batter_id'], ['players.player_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opp_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pitcher_id'], ['players.player_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'play_num')
    )
    op.create_table('baseball_bullpen',
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('opp_id', sa.Integer(), nullable=False),
    sa.Column('pitch_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opp_id'], ['teams.team_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('game_id', 'player_id')
    )
    op.create_table('baseball_lineup',
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('opp_id', sa.Integer(), nullable=False),
    sa.Column('batt_order', sa.Integer(), nullable=False),
    sa.Column('sub_order', sa.Integer(), nullable=True),
    sa.Column('pos', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opp_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'player_id')
    )
    op.create_table('basketball_player_stats',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('opp_id', sa.Integer(), nullable=False),
    sa.Column('starter', sa.Boolean(), nullable=False),
    sa.Column('mins', sa.Float(), nullable=False),
    sa.Column('fga', sa.Integer(), nullable=False),
    sa.Column('fgm', sa.Integer(), nullable=False),
    sa.Column('fta', sa.Integer(), nullable=False),
    sa.Column('ftm', sa.Integer(), nullable=False),
    sa.Column('tpa', sa.Integer(), nullable=False),
    sa.Column('tpm', sa.Integer(), nullable=False),
    sa.Column('pts', sa.Integer(), nullable=False),
    sa.Column('oreb', sa.Integer(), nullable=False),
    sa.Column('dreb', sa.Integer(), nullable=False),
    sa.Column('ast', sa.Integer(), nullable=False),
    sa.Column('stl', sa.Integer(), nullable=False),
    sa.Column('blk', sa.Integer(), nullable=False),
    sa.Column('turns', sa.Integer(), nullable=False),
    sa.Column('fls', sa.Integer(), nullable=False),
    sa.Column('plus_minus', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opp_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id', 'game_id')
    )
    op.create_table('basketball_shots',
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('play_num', sa.String(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('opp_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('shot_type_id', sa.Integer(), nullable=False),
    sa.Column('assist_id', sa.Integer(), nullable=True),
    sa.Column('shot_made', sa.Boolean(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('base_pct', sa.Float(), nullable=False),
    sa.Column('side_pct', sa.Float(), nullable=False),
    sa.Column('distance', sa.Integer(), nullable=False),
    sa.Column('fastbreak', sa.Boolean(), nullable=False),
    sa.Column('side_of_basket', sa.String(), nullable=False),
    sa.Column('clutch', sa.Boolean(), nullable=True),
    sa.Column('zone', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['assist_id'], ['players.player_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opp_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shot_type_id'], ['basketball_shot_types.shot_type_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'play_num')
    )
    op.create_table('batting_stats',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('opp_id', sa.Integer(), nullable=False),
    sa.Column('ab', sa.Integer(), nullable=False),
    sa.Column('bb', sa.Integer(), nullable=False),
    sa.Column('r', sa.Integer(), nullable=False),
    sa.Column('h', sa.Integer(), nullable=False),
    sa.Column('hr', sa.Integer(), nullable=False),
    sa.Column('rbi', sa.Integer(), nullable=False),
    sa.Column('sb', sa.Integer(), nullable=False),
    sa.Column('so', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opp_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id', 'game_id')
    )
    op.create_table('defense',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('opp_id', sa.Integer(), nullable=False),
    sa.Column('tackles', sa.Integer(), nullable=False),
    sa.Column('sacks', sa.Float(), nullable=False),
    sa.Column('ints', sa.Integer(), nullable=False),
    sa.Column('pass_def', sa.Integer(), nullable=False),
    sa.Column('qb_hits', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opp_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id', 'game_id')
    )
    op.create_table('fumbles',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('opp_id', sa.Integer(), nullable=False),
    sa.Column('fum_lost', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opp_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id', 'game_id')
    )
    op.create_table('kick_plays',
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('play_num', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('opp_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('down', sa.Integer(), nullable=False),
    sa.Column('distance', sa.Integer(), nullable=False),
    sa.Column('clock', sa.Float(), nullable=False),
    sa.Column('kicker', sa.Integer(), nullable=False),
    sa.Column('yards', sa.Integer(), nullable=False),
    sa.Column('kick_good', sa.Boolean(), nullable=False),
    sa.Column('kick_blocked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kicker'], ['players.player_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opp_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'play_num')
    )
    op.create_table('kick_returns',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('opp_id', sa.Integer(), nullable=False),
    sa.Column('kr', sa.Integer(), nullable=False),
    sa.Column('kr_yds', sa.Integer(), nullable=False),
    sa.Column('kr_td', sa.Integer(), nullable=False),
    sa.Column('pr', sa.Integer(), nullable=False),
    sa.Column('pr_yds', sa.Integer(), nullable=False),
    sa.Column('pr_td', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opp_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id', 'game_id')
    )
    op.create_table('pass_plays',
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('play_num', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('opp_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('down', sa.Integer(), nullable=False),
    sa.Column('distance', sa.Integer(), nullable=False),
    sa.Column('clock', sa.Float(), nullable=False),
    sa.Column('yards_to_endzone', sa.Integer(), nullable=False),
    sa.Column('quarterback', sa.Integer(), nullable=False),
    sa.Column('target', sa.Integer(), nullable=True),
    sa.Column('yards', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('touchdown', sa.Boolean(), nullable=False),
    sa.Column('intercepted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opp_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quarterback'], ['players.player_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target'], ['players.player_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'play_num')
    )
    op.create_table('passing',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('opp_id', sa.Integer(), nullable=False),
    sa.Column('pass_att', sa.Integer(), nullable=False),
    sa.Column('pass_comp', sa.Integer(), nullable=False),
    sa.Column('pass_yds', sa.Integer(), nullable=False),
    sa.Column('pass_td', sa.Integer(), nullable=False),
    sa.Column('pass_int', sa.Integer(), nullable=False),
    sa.Column('sacks', sa.Integer(), nullable=False),
    sa.Column('sack_yds_lost', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opp_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id', 'game_id')
    )
    op.create_table('pitches',
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('play_num', sa.String(), nullable=False),
    sa.Column('pitcher_id', sa.Integer(), nullable=False),
    sa.Column('batter_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('opp_id', sa.Integer(), nullable=False),
    sa.Column('pitch_count', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('balls', sa.Integer(), nullable=False),
    sa.Column('strikes', sa.Integer(), nullable=False),
    sa.Column('velocity', sa.Integer(), nullable=False),
    sa.Column('pitch_x', sa.Integer(), nullable=False),
    sa.Column('pitch_y', sa.Integer(), nullable=False),
    sa.Column('pitch_location', sa.Integer(), nullable=False),
    sa.Column('pitch_type_name', sa.String(), nullable=False),
    sa.Column('ab_result_name', sa.String(), nullable=True),
    sa.Column('pitch_result_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['batter_id'], ['players.player_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opp_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pitch_result_name'], ['pitch_result_types.pitch_result_name'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pitcher_id'], ['players.player_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'play_num')
    )
    op.create_table('pitching_stats',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('opp_id', sa.Integer(), nullable=False),
    sa.Column('full_ip', sa.Integer(), nullable=False),
    sa.Column('partial_ip', sa.Integer(), nullable=False),
    sa.Column('bba', sa.Integer(), nullable=False),
    sa.Column('ha', sa.Integer(), nullable=False),
    sa.Column('hra', sa.Integer(), nullable=False),
    sa.Column('k', sa.Integer(), nullable=False),
    sa.Column('ra', sa.Integer(), nullable=False),
    sa.Column('er', sa.Integer(), nullable=False),
    sa.Column('w', sa.Integer(), nullable=False),
    sa.Column('l', sa.Integer(), nullable=False),
    sa.Column('sv', sa.Integer(), nullable=False),
    sa.Column('blsv', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opp_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id', 'game_id')
    )
    op.create_table('punts',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('opp_id', sa.Integer(), nullable=False),
    sa.Column('punts', sa.Integer(), nullable=False),
    sa.Column('punt_yds', sa.Integer(), nullable=False),
    sa.Column('in20', sa.Integer(), nullable=True),
    sa.Column('touchback', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opp_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id', 'game_id')
    )
    op.create_table('receiving',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('opp_id', sa.Integer(), nullable=False),
    sa.Column('tgt', sa.Integer(), nullable=True),
    sa.Column('rec', sa.Integer(), nullable=False),
    sa.Column('rec_yds', sa.Integer(), nullable=False),
    sa.Column('rec_td', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opp_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id', 'game_id')
    )
    op.create_table('rush_plays',
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('play_num', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('opp_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('down', sa.Integer(), nullable=False),
    sa.Column('distance', sa.Integer(), nullable=False),
    sa.Column('clock', sa.Float(), nullable=False),
    sa.Column('yards_to_endzone', sa.Integer(), nullable=False),
    sa.Column('rusher', sa.Integer(), nullable=False),
    sa.Column('yards', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Integer(), nullable=False),
    sa.Column('touchdown', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opp_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rusher'], ['players.player_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'play_num')
    )
    op.create_table('rushing',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('opp_id', sa.Integer(), nullable=False),
    sa.Column('rush_att', sa.Integer(), nullable=False),
    sa.Column('rush_yds', sa.Integer(), nullable=False),
    sa.Column('rush_td', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opp_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id', 'game_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rushing')
    op.drop_table('rush_plays')
    op.drop_table('receiving')
    op.drop_table('punts')
    op.drop_table('pitching_stats')
    op.drop_table('pitches')
    op.drop_table('passing')
    op.drop_table('pass_plays')
    op.drop_table('kick_returns')
    op.drop_table('kick_plays')
    op.drop_table('fumbles')
    op.drop_table('defense')
    op.drop_table('batting_stats')
    op.drop_table('basketball_shots')
    op.drop_table('basketball_player_stats')
    op.drop_table('baseball_lineup')
    op.drop_table('baseball_bullpen')
    op.drop_table('at_bats')
    op.drop_table('pitch_result_types')
    op.drop_table('basketball_shot_types')
    op.drop_table('at_bat_types')
    # ### end Alembic commands ###
