"""adds gaming tables

Revision ID: 68dffc9d41be
Revises: bff25a74dd16
Create Date: 2025-08-16 19:38:14.490417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68dffc9d41be'
down_revision: Union[str, None] = 'bff25a74dd16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_lines',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('opp_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('spread', sa.Float(), nullable=False),
    sa.Column('spread_line', sa.Integer(), nullable=True),
    sa.Column('money_line', sa.Integer(), nullable=True),
    sa.Column('result', sa.Integer(), nullable=False),
    sa.Column('spread_outcome', sa.Integer(), nullable=False),
    sa.Column('money_outcome', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opp_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'game_id')
    )
    op.create_table('over_unders',
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('over_under', sa.Float(), nullable=False),
    sa.Column('over_line', sa.Integer(), nullable=True),
    sa.Column('under_line', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('ou_outcome', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('over_unders')
    op.drop_table('game_lines')
    # ### end Alembic commands ###
