"""adds team stats

Revision ID: 7a00ca15f365
Revises: 68dffc9d41be
Create Date: 2025-08-17 10:04:30.551118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a00ca15f365'
down_revision: Union[str, None] = '68dffc9d41be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baseball_team_stats',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('opp_id', sa.Integer(), nullable=False),
    sa.Column('ab', sa.Integer(), nullable=False),
    sa.Column('bb', sa.Integer(), nullable=False),
    sa.Column('r', sa.Integer(), nullable=False),
    sa.Column('h', sa.Integer(), nullable=False),
    sa.Column('hr', sa.Integer(), nullable=False),
    sa.Column('rbi', sa.Integer(), nullable=False),
    sa.Column('sb', sa.Integer(), nullable=False),
    sa.Column('lob', sa.Integer(), nullable=False),
    sa.Column('full_ip', sa.Integer(), nullable=False),
    sa.Column('partial_ip', sa.Integer(), nullable=False),
    sa.Column('bba', sa.Integer(), nullable=False),
    sa.Column('ha', sa.Integer(), nullable=False),
    sa.Column('ra', sa.Integer(), nullable=False),
    sa.Column('hra', sa.Integer(), nullable=False),
    sa.Column('er', sa.Integer(), nullable=False),
    sa.Column('k', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opp_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'game_id')
    )
    op.create_table('basketball_team_stats',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('opp_id', sa.Integer(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('fga', sa.Integer(), nullable=False),
    sa.Column('fgm', sa.Integer(), nullable=False),
    sa.Column('fta', sa.Integer(), nullable=False),
    sa.Column('ftm', sa.Integer(), nullable=False),
    sa.Column('tpa', sa.Integer(), nullable=False),
    sa.Column('tpm', sa.Integer(), nullable=False),
    sa.Column('pts', sa.Integer(), nullable=False),
    sa.Column('oreb', sa.Integer(), nullable=False),
    sa.Column('dreb', sa.Integer(), nullable=False),
    sa.Column('ast', sa.Integer(), nullable=False),
    sa.Column('stl', sa.Integer(), nullable=False),
    sa.Column('blk', sa.Integer(), nullable=False),
    sa.Column('turns', sa.Integer(), nullable=False),
    sa.Column('fouls', sa.Integer(), nullable=False),
    sa.Column('fb_pts', sa.Integer(), nullable=True),
    sa.Column('pts_in_pt', sa.Integer(), nullable=True),
    sa.Column('poss', sa.Integer(), sa.Computed('fga + 0.44 * fta - oreb + turns', ), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opp_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'game_id')
    )
    op.create_table('football_team_stats',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('opp_id', sa.Integer(), nullable=False),
    sa.Column('pts', sa.Integer(), nullable=False),
    sa.Column('drives', sa.Integer(), nullable=True),
    sa.Column('plays', sa.Integer(), nullable=False),
    sa.Column('yards', sa.Integer(), nullable=False),
    sa.Column('pass_plays', sa.Integer(), nullable=False),
    sa.Column('pass_yards', sa.Integer(), nullable=False),
    sa.Column('rush_plays', sa.Integer(), nullable=False),
    sa.Column('rush_yards', sa.Integer(), nullable=False),
    sa.Column('int_thrown', sa.Integer(), nullable=False),
    sa.Column('fum_lost', sa.Integer(), nullable=False),
    sa.Column('times_sacked', sa.Integer(), nullable=False),
    sa.Column('sack_yds_lost', sa.Integer(), nullable=False),
    sa.Column('penalties', sa.Integer(), nullable=False),
    sa.Column('penalty_yards', sa.Integer(), nullable=False),
    sa.Column('time_of_poss', sa.Float(), nullable=False),
    sa.Column('third_att', sa.Integer(), nullable=False),
    sa.Column('third_conv', sa.Integer(), nullable=False),
    sa.Column('fourth_att', sa.Integer(), nullable=False),
    sa.Column('fourth_conv', sa.Integer(), nullable=False),
    sa.Column('rz_att', sa.Integer(), nullable=True),
    sa.Column('rz_conv', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opp_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'game_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('football_team_stats')
    op.drop_table('basketball_team_stats')
    op.drop_table('baseball_team_stats')
    # ### end Alembic commands ###
