"""remove blsv

Revision ID: 87a9e7a891ab
Revises: f87d9532764d
Create Date: 2025-10-20 16:03:45.454669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87a9e7a891ab'
down_revision: Union[str, None] = 'f87d9532764d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitching_stats', 'blsv')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitching_stats', sa.Column('blsv', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
