"""adding rec fields

Revision ID: 91b785be9cf8
Revises: db9d83d051d5
Create Date: 2025-10-20 20:04:36.198133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91b785be9cf8'
down_revision: Union[str, None] = 'db9d83d051d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receiving', sa.Column('yac', sa.Integer(), nullable=True))
    op.add_column('receiving', sa.Column('rec_1d', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receiving', 'rec_1d')
    op.drop_column('receiving', 'yac')
    # ### end Alembic commands ###
