"""adding team fg attempts

Revision ID: 97347d6b6812
Revises: 91b785be9cf8
Create Date: 2025-11-02 15:06:43.901058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97347d6b6812'
down_revision: Union[str, None] = '91b785be9cf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('football_team_stats', sa.Column('fg_att', sa.Integer(), nullable=False))
    op.add_column('football_team_stats', sa.Column('fg_conv', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('football_team_stats', 'fg_conv')
    op.drop_column('football_team_stats', 'fg_att')
    # ### end Alembic commands ###
