"""remove plays

Revision ID: db9d83d051d5
Revises: 87a9e7a891ab
Create Date: 2025-10-20 20:01:40.588173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db9d83d051d5'
down_revision: Union[str, None] = '87a9e7a891ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('football_team_stats', 'plays')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('football_team_stats', sa.Column('plays', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
