"""change sack requirements

Revision ID: ddc1e871d0d7
Revises: 08ad56e0dc1f
Create Date: 2025-11-11 16:43:23.184486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddc1e871d0d7'
down_revision: Union[str, None] = '08ad56e0dc1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('football_team_stats', 'times_sacked',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('football_team_stats', 'sack_yds_lost',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('football_team_stats', 'sack_yds_lost',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('football_team_stats', 'times_sacked',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
