"""adds analytic tables

Revision ID: eb7e23096845
Revises: 23673d16539b
Create Date: 2025-09-04 16:41:26.869799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb7e23096845'
down_revision: Union[str, None] = '23673d16539b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league_metrics',
    sa.Column('league_id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('away_home', sa.String(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('best_value', sa.Numeric(), nullable=True),
    sa.Column('worst_value', sa.Numeric(), nullable=True),
    sa.Column('q1', sa.Numeric(), nullable=True),
    sa.Column('q2', sa.Numeric(), nullable=True),
    sa.Column('q4', sa.Numeric(), nullable=True),
    sa.Column('q6', sa.Numeric(), nullable=True),
    sa.Column('q8', sa.Numeric(), nullable=True),
    sa.Column('q9', sa.Numeric(), nullable=True),
    sa.Column('reference_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.league_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('league_id', 'entity_type', 'timeframe', 'away_home', 'metric_name')
    )
    op.create_table('stat_metrics',
    sa.Column('league_id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('away_home', sa.String(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=True),
    sa.Column('reference_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.league_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('league_id', 'entity_type', 'entity_id', 'timeframe', 'away_home', 'metric_name')
    )
    op.drop_index('idx_provider_mapping_entity_id', table_name='provider_mapping')
    op.create_index(op.f('ix_provider_mapping_entity_id'), 'provider_mapping', ['entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_provider_mapping_entity_id'), table_name='provider_mapping')
    op.create_index('idx_provider_mapping_entity_id', 'provider_mapping', ['entity_id'], unique=False)
    op.drop_table('stat_metrics')
    op.drop_table('league_metrics')
    # ### end Alembic commands ###
