"""base configuration

Revision ID: f77663cd2bb9
Revises: 
Create Date: 2025-08-12 14:22:54.200763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f77663cd2bb9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('org_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('abrv', sa.String(), nullable=False),
    sa.Column('primary_color', sa.String(), nullable=True),
    sa.Column('secondary_color', sa.String(), nullable=True),
    sa.Column('org_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('org_id')
    )
    op.create_table('providers',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('sports',
    sa.Column('sport_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('sport_id')
    )
    op.create_table('leagues',
    sa.Column('league_id', sa.String(), nullable=False),
    sa.Column('sport_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sched_type', sa.String(), nullable=False),
    sa.Column('curr_season', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('last_update', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.sport_id'], ),
    sa.PrimaryKeyConstraint('league_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('provider_mapping',
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('league_id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.league_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider'], ['providers.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('provider', 'league_id', 'entity_type', 'provider_id'),
    sa.Index('idx_provider_mapping_entity_id', 'entity_id')  # Add index here
    )
    op.create_table('weeks',
    sa.Column('league_id', sa.String(), nullable=False),
    sa.Column('week_num', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.league_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('league_id', 'week_num'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weeks')
    op.drop_table('provider_mapping')
    op.drop_table('leagues')
    op.drop_table('sports')
    op.drop_table('providers')
    op.drop_table('organizations')
    # ### end Alembic commands ###
