"""adds wager/stake data

Revision ID: f87d9532764d
Revises: eb7e23096845
Create Date: 2025-10-20 15:33:19.251053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f87d9532764d'
down_revision: Union[str, None] = 'eb7e23096845'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_lines', sa.Column('spread_wager_pct', sa.Float(), nullable=True))
    op.add_column('game_lines', sa.Column('spread_stake_pct', sa.Float(), nullable=True))
    op.add_column('game_lines', sa.Column('money_wager_pct', sa.Float(), nullable=True))
    op.add_column('game_lines', sa.Column('money_stake_pct', sa.Float(), nullable=True))
    op.drop_column('stat_metrics', 'away_home')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stat_metrics', sa.Column('away_home', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('game_lines', 'money_stake_pct')
    op.drop_column('game_lines', 'money_wager_pct')
    op.drop_column('game_lines', 'spread_stake_pct')
    op.drop_column('game_lines', 'spread_wager_pct')
    # ### end Alembic commands ###
